/* Generated By:JavaCC: Do not edit this line. ParserBCConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserBCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_LINHA = 6;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 10;
  /** RegularExpression Id. */
  int SEPARADOR = 11;
  /** RegularExpression Id. */
  int DEFINICAO = 12;
  /** RegularExpression Id. */
  int ABRE_COLCHETE = 13;
  /** RegularExpression Id. */
  int FECHA_COLCHETE = 14;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 15;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 16;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 17;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 18;
  /** RegularExpression Id. */
  int IGUAL = 19;
  /** RegularExpression Id. */
  int ASPAS_DUPLAS = 20;
  /** RegularExpression Id. */
  int OU_LOGICO = 21;
  /** RegularExpression Id. */
  int E_LOGICO = 22;
  /** RegularExpression Id. */
  int NEGACAO = 23;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 24;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 25;
  /** RegularExpression Id. */
  int DIFERENTE = 26;
  /** RegularExpression Id. */
  int MENOR = 27;
  /** RegularExpression Id. */
  int MAIOR = 28;
  /** RegularExpression Id. */
  int ATRIBUI = 29;
  /** RegularExpression Id. */
  int ATRIBUI_SOMANDO = 30;
  /** RegularExpression Id. */
  int ATRIBUI_SUBTRAINDO = 31;
  /** RegularExpression Id. */
  int ATRIBUI_MULTIPLICANDO = 32;
  /** RegularExpression Id. */
  int ATRIBUI_DIVINDO = 33;
  /** RegularExpression Id. */
  int ATRIBUI_RESTO = 34;
  /** RegularExpression Id. */
  int ATRIBUI_POTENCIA = 35;
  /** RegularExpression Id. */
  int SOMA = 36;
  /** RegularExpression Id. */
  int SUBTRACAO = 37;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 38;
  /** RegularExpression Id. */
  int DIVISAO = 39;
  /** RegularExpression Id. */
  int RESTO = 40;
  /** RegularExpression Id. */
  int POTENCIA = 41;
  /** RegularExpression Id. */
  int INCREMENTO = 42;
  /** RegularExpression Id. */
  int DECREMENTO = 43;
  /** RegularExpression Id. */
  int PONTO = 44;
  /** RegularExpression Id. */
  int VIRGULA = 45;
  /** RegularExpression Id. */
  int AUTO = 46;
  /** RegularExpression Id. */
  int IF = 47;
  /** RegularExpression Id. */
  int ELSE = 48;
  /** RegularExpression Id. */
  int WHILE = 49;
  /** RegularExpression Id. */
  int FOR = 50;
  /** RegularExpression Id. */
  int NULL = 51;
  /** RegularExpression Id. */
  int BREAK = 52;
  /** RegularExpression Id. */
  int CONTINUE = 53;
  /** RegularExpression Id. */
  int QUIT = 54;
  /** RegularExpression Id. */
  int PRINT = 55;
  /** RegularExpression Id. */
  int RAIZ_QUADRADA = 56;
  /** RegularExpression Id. */
  int TAMANHO = 57;
  /** RegularExpression Id. */
  int ESCALA = 58;
  /** RegularExpression Id. */
  int IBASE = 59;
  /** RegularExpression Id. */
  int OBASE = 60;
  /** RegularExpression Id. */
  int LAST = 61;
  /** RegularExpression Id. */
  int RETORNO = 62;
  /** RegularExpression Id. */
  int ID = 63;
  /** RegularExpression Id. */
  int LETRA = 64;
  /** RegularExpression Id. */
  int INTEIRO = 65;
  /** RegularExpression Id. */
  int REAL = 66;
  /** RegularExpression Id. */
  int ENDSTRING = 67;
  /** RegularExpression Id. */
  int STRING = 68;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENTARIO_MULTILINHA = 1;
  /** Lexical state. */
  int ESTADO_STRING = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMENTARIO_LINHA>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\";\"",
    "<SEPARADOR>",
    "\"define\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"==\"",
    "\"\\\"\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"^=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"++\"",
    "\"--\"",
    "\".\"",
    "\",\"",
    "\"auto\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "<NULL>",
    "\"break\"",
    "\"continue\"",
    "\"quit\"",
    "\"print\"",
    "\"sqrt\"",
    "\"lenght\"",
    "\"scale\"",
    "\"ibase\"",
    "\"obase\"",
    "\"last\"",
    "\"return\"",
    "<ID>",
    "<LETRA>",
    "<INTEIRO>",
    "<REAL>",
    "<ENDSTRING>",
    "<STRING>",
    "\"s\"",
    "\"c\"",
    "\"e\"",
    "\"l\"",
    "\"a\"",
    "\"j\"",
  };

}
